services:
  allopito:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=allopito
      - MYSQL_ROOT_PASSWORD=Oxymore
    ports:
      - 3307:3306
    volumes:
          - ./:/docker-entrypoint-initdb.d
          - allopito:/var/lib/mysql
          
volumes:
    allopito:
      driver: local
        
    
